### PR TITLE
Enable and fix Eslint checks on GitHub Actions

### PR DESCRIPTION
**Pull request by Gustry**
* Enable and fix Eslint checks on GitHub Actions

@nboisteault What do you think ?

The unused variable uncheck seems verbose to me. Isn't there another way ?

Then for others, I'm not sure if it was not false positive error or not.

### CODE REVIEW

**Comment by nboisteault** [comment]
@Gustry @drillinP : this JS code will change a lot and we'll take care of unused variable.

**Comment by Gustry** [comment]
Do you mean we merge this PR and we give it a try ? @nboisteault 

If it's too much, we can review the config in a few days.

**Comment by nboisteault** [comment]
I thunk you can merge all but pgmetadata.js

**Comment by Gustry** [comment]
Ok, I have removed my changes on pgmetadata.js.
Now, the CI is failing. @drillinP You would need to rebase your PR and include fixes about EsLint.

**Pull request merged**
